'use strict';var Markdown={};
(function(){function m(f){return f}function x(){return!1}function q(){}function u(){}q.prototype={chain:function(f,n){var t=this[f];if(!t)throw Error("unknown hook "+f);this[f]=t===m?n:function(f){var o=Array.prototype.slice.call(arguments,0);o[0]=t.apply(null,o);return n.apply(null,o)}},set:function(f,n){if(!this[f])throw Error("unknown hook "+f);this[f]=n},addNoop:function(f){this[f]=m},addFalse:function(f){this[f]=x}};Markdown.HookCollection=q;u.prototype={set:function(f,n){this["s_"+f]=n},get:function(f){return this["s_"+
f]}};Markdown.Converter=function(){function f(a){return a=a.replace(/^[ ]{0,3}\[(.+)\]:[ \t]*\n?[ \t]*<?(\S+?)>?(?=\s|$)[ \t]*\n?[ \t]*((\n*)["(](.+?)[")][ \t]*)?(?:\n+)/gm,function(a,d,L,c,e,l){d=d.toLowerCase();F.set(d,b(L));if(e)return c;l&&G.set(d,l.replace(/"/g,"&quot;"));return""})}function n(a){a=a.replace(/^(<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math|ins|del)\b[^\r]*?\n<\/\2>[ \t]*(?=\n+))/gm,m);a=a.replace(/^(<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math)\b[^\r]*?.*<\/\2>[ \t]*(?=\n+)\n)/gm,
m);a=a.replace(/\n[ ]{0,3}((<(hr)\b([^<>])*?\/?>)[ \t]*(?=\n{2,}))/g,m);a=a.replace(/\n\n[ ]{0,3}(<!(--(?:|(?:[^>-]|-[^>])(?:[^-]|-[^-])*)--)>[ \t]*(?=\n{2,}))/g,m);return a=a.replace(/(?:\n\n)([ ]{0,3}(?:<([?%])[^\r]*?\2>)[ \t]*(?=\n{2,}))/g,m)}function m(a,b){var d;d=b.replace(/^\n+/,"");d=d.replace(/\n+$/g,"");return d="\n\n~K"+(H.push(d)-1)+"K\n\n"}function s(a,b){a=z.preBlockGamut(a,K);a=B(a);a=a.replace(/^[ ]{0,2}([ ]?\*[ ]?){3,}[ \t]*$/gm,"<hr />\n");a=a.replace(/^[ ]{0,2}([ ]?-[ ]?){3,}[ \t]*$/gm,
"<hr />\n");a=a.replace(/^[ ]{0,2}([ ]?_[ ]?){3,}[ \t]*$/gm,"<hr />\n");a=i(a);a=E(a);a=e(a);a=z.postBlockGamut(a,K);a=n(a);return a=c(a,b)}function o(a){a=z.preSpanGamut(a);a=v(a);a=x(a);a=a.replace(/\\(\\)/g,A);a=a.replace(/\\([`*_{}\[\]()>#+-.!])/g,A);a=a.replace(/(!\[(.*?)\][ ]?(?:\n[ ]*)?\[(.*?)\])()()()()/g,p);a=a.replace(/(!\[(.*?)\]\s?\([ \t]*()<?(\S+?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,p);a=a.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\][ ]?(?:\n[ ]*)?\[(.*?)\])()()()()/g,y);a=a.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\]\([ \t]*()<?((?:\([^)]*\)|[^()\s])*?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,
y);a=a.replace(/(\[([^\[\]]+)\])()()()()()/g,y);a=g(a);a=a.replace(/~P/g,"://");a=b(a);a=a.replace(/([\W_]|^)(\*\*|__)(?=\S)([^\r]*?\S[\*_]*)\2([\W_]|$)/g,"$1<strong>$3</strong>$4");a=a.replace(/([\W_]|^)(\*|_)(?=\S)([^\r\*_]*?\S)\2([\W_]|$)/g,"$1<em>$3</em>$4");a=a.replace(/  +\n/g," <br>\n");return a=z.postSpanGamut(a)}function x(a){return a=a.replace(/(<[a-z\/!$]("[^"]*"|'[^']*'|[^'">])*>|<!(--(?:|(?:[^>-]|-[^>])(?:[^-]|-[^-])*)--)>)/gi,function(a){var b=a.replace(/(.)<\/?code>(?=.)/g,"$1`");return b=
r(b,"!"==a.charAt(1)?"\\`*_/":"\\`*_")})}function y(a,b,d,c,e,k,g,A){void 0==A&&(A="");a=d.replace(/:\/\//g,"~P");c=c.toLowerCase();if(""==e)if(""==c&&(c=a.toLowerCase().replace(/ ?\n/g," ")),void 0!=F.get(c))e=F.get(c),void 0!=G.get(c)&&(A=G.get(c));else if(-1<b.search(/\(\s*\)$/m))e="";else return b;e=l(e);e=r(e,"*_");b='<a href="'+e+'"';""!=A&&(A=j(A),A=r(A,"*_"),b+=' title="'+A+'"');return b+(">"+a+"</a>")}function j(a){return a.replace(/>/g,"&gt;").replace(/</g,"&lt;").replace(/"/g,"&quot;")}
function p(a,b,d,c,e,l,k,g){a=d;c=c.toLowerCase();g||(g="");if(""==e)if(""==c&&(c=a.toLowerCase().replace(/ ?\n/g," ")),void 0!=F.get(c))e=F.get(c),void 0!=G.get(c)&&(g=G.get(c));else return b;a=r(j(a),"*_[]()");e=r(e,"*_");b='<img src="'+e+'" alt="'+a+'"';g=j(g);g=r(g,"*_");return b+(' title="'+g+'"')+" />"}function B(a){a=a.replace(/^(.+)[ \t]*\n=+[ \t]*\n+/gm,function(a,b){return"<h1>"+o(b)+"</h1>\n\n"});a=a.replace(/^(.+)[ \t]*\n-+[ \t]*\n+/gm,function(a,b){return"<h2>"+o(b)+"</h2>\n\n"});return a=
a.replace(/^(\#{1,6})[ \t]*(.+?)[ \t]*\#*\n+/gm,function(a,b,d){a=b.length;return"<h"+a+">"+o(d)+"</h"+a+">\n\n"})}function i(a,b){var a=a+"~0",d=/^(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/gm;J?a=a.replace(d,function(a,d,c){a=-1<c.search(/[*+-]/g)?"ul":"ol";d=w(d,a,b);d=d.replace(/\s+$/,"");return"<"+a+">"+d+"</"+a+">\n"}):(d=/(\n\n|^\n?)(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/g,a=a.replace(d,function(a,
b,d,c){a=-1<c.search(/[*+-]/g)?"ul":"ol";d=w(d,a);return b+"<"+a+">\n"+d+"</"+a+">\n"}));return a=a.replace(/~0/,"")}function w(a,b,d){J++;var a=a.replace(/\n{2,}$/,"\n"),b=M[b],c=!1,a=(a+"~0").replace(RegExp("(^[ \\t]*)("+b+")[ \\t]+([^\\r]+?(\\n+))(?=(~0|\\1("+b+")[ \\t]+))","gm"),function(a,b,e,l){a=l;(b=/\n\n$/.test(a))||-1<a.search(/\n{2,}/)||c?a=s(I(a),!0):(a=i(I(a),!0),a=a.replace(/\n$/,""),d||(a=o(a)));c=b;return"<li>"+a+"</li>\n"}),a=a.replace(/~0/g,"");J--;return a}function E(b){b=(b+"~0").replace(/(?:\n\n|^\n?)((?:(?:[ ]{4}|\t).*\n+)+)(\n*[ ]{0,3}[^ \t\n]|(?=~0))/g,
function(b,d,c){b=a(I(d));b=D(b);b=b.replace(/^\n+/g,"");b=b.replace(/\n+$/g,"");return"\n\n"+("<pre><code>"+b+"\n</code></pre>")+"\n\n"+c});return b=b.replace(/~0/,"")}function h(a){a=a.replace(/(^\n+|\n+$)/g,"");return"\n\n~K"+(H.push(a)-1)+"K\n\n"}function v(b){return b=b.replace(/(^|[^\\])(`+)([^\r]*?[^`])\2(?!`)/gm,function(b,d,c,e){b=e.replace(/^([ \t]*)/g,"");b=b.replace(/[ \t]*$/g,"");b=a(b);b=b.replace(/:\/\//g,"~P");return d+"<code>"+b+"</code>"})}function a(a){a=a.replace(/&/g,"&amp;");
a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;");return a=r(a,"*_{}[]\\",!1)}function e(a){return a=a.replace(/((^[ \t]*>[ \t]?.+\n(.+\n)*\n*)+)/gm,function(a,b){var d;d=b.replace(/^[ \t]*>[ \t]?/gm,"~0");d=d.replace(/~0/g,"");d=d.replace(/^[ \t]+$/gm,"");d=s(d);d=d.replace(/(^|\n)/g,"$1  ");d=d.replace(/(\s*<pre>[^\r]+?<\/pre>)/gm,function(a,b){var d;d=b.replace(/^  /mg,"~0");return d=d.replace(/~0/g,"")});return h("<blockquote>\n"+d+"\n</blockquote>")})}function c(a,b){for(var a=a.replace(/^\n+/g,
""),a=a.replace(/\n+$/g,""),d=a.split(/\n{2,}/g),c=[],e=/~K(\d+)K/,l=d.length,g=0;g<l;g++){var r=d[g];e.test(r)?c.push(r):/\S/.test(r)&&(r=o(r),r=r.replace(/^([ \t]*)/g,"<p>"),r+="</p>",c.push(r))}if(!b){l=c.length;for(g=0;g<l;g++)for(var k=!0;k;)k=!1,c[g]=c[g].replace(/~K(\d+)K/g,function(a,b){k=!0;return H[b]})}return c.join("\n\n")}function b(a){a=a.replace(/&(?!#?[xX]?(?:[0-9a-fA-F]+|\w+);)/g,"&amp;");return a=a.replace(/<(?![a-z\/?!]|~D)/gi,"&lt;")}function d(a,b,d,c){if(b)return a;if(")"!==
c.charAt(c.length-1))return"<"+d+c+">";for(var a=c.match(/[()]/g),e=b=0;e<a.length;e++)"("===a[e]?0>=b?b=1:b++:b--;var l="";0>b&&(c=c.replace(RegExp("\\){1,"+-b+"}$"),function(a){l=a;return""}));l&&(a=c.charAt(c.length-1),N.test(a)||(l=a+l,c=c.substr(0,c.length-1)));return"<"+d+c+">"+l}function g(a){a=a.replace(O,d);return a=a.replace(/<((https?|ftp):[^'">\s]+)>/gi,function(a,b){return'<a href="'+b+'">'+z.plainLinkText(b)+"</a>"})}function k(a){return a=a.replace(/~E(\d+)E/g,function(a,b){var d=parseInt(b);
return String.fromCharCode(d)})}function I(a){a=a.replace(/^(\t|[ ]{1,4})/gm,"~0");return a=a.replace(/~0/g,"")}function D(a){if(!/\t/.test(a))return a;var b=["    ","   ","  "," "],d=0,c;return a.replace(/[\n\t]/g,function(a,e){if("\n"===a)return d=e+1,a;c=(e-d)%4;d=e+1;return b[c]})}function l(a){if(!a)return"";var b=a.length;return a.replace(P,function(d,c){return"~D"==d?"%24":":"==d&&(c==b-1||/[0-9\/]/.test(a.charAt(c+1)))?":":"%"+d.charCodeAt(0).toString(16)})}function r(a,b,d){b="(["+b.replace(/([\[\]\\])/g,
"\\$1")+"])";d&&(b="\\\\"+b);return a=a.replace(RegExp(b,"g"),A)}function A(a,b){return"~E"+b.charCodeAt(0)+"E"}var z=this.hooks=new q;z.addNoop("plainLinkText");z.addNoop("preConversion");z.addNoop("postNormalization");z.addNoop("preBlockGamut");z.addNoop("postBlockGamut");z.addNoop("preSpanGamut");z.addNoop("postSpanGamut");z.addNoop("postConversion");var F,G,H,J;this.makeHtml=function(a){if(F)throw Error("Recursive call to converter.makeHtml");F=new u;G=new u;H=[];J=0;a=z.preConversion(a);a=a.replace(/~/g,
"~T");a=a.replace(/\$/g,"~D");a=a.replace(/\r\n/g,"\n");a=a.replace(/\r/g,"\n");a=D("\n\n"+a+"\n\n");a=a.replace(/^[ \t]+$/mg,"");a=z.postNormalization(a);a=n(a);a=f(a);a=s(a);a=k(a);a=a.replace(/~D/g,"$$");a=a.replace(/~T/g,"~");a=z.postConversion(a);H=G=F=null;return a};var K=function(a){return s(a)},M={ol:"\\d+[.]",ul:"[*+-]"},O=/(="|<)?\b(https?|ftp)(:\/\/[-A-Z0-9+&@#/%?=~_|[\]()!:,.;]*[-A-Z0-9+&@#/%=~_|[\])])(?=$|\W)/gi,N=/[-A-Z0-9+&@#/%=~_|[\])]/i,P=/(?:["'*()[\]:]|~D)/g}})();
(function(){var m,x,q;function u(){}function f(a){this.buttonBar=i.getElementById("wmd-button-bar"+a);this.preview=i.getElementById("wmd-preview"+a);this.input=i.getElementById("wmd-input"+a)}function n(a,e){var c=this,b=[],d=0,g="none",k,h,D,l=function(a,b){g!=a&&(g=a,b||A());!m||"moving"!=g?h=setTimeout(r,1):D=null},r=function(a){D=new t(e,a);h=void 0};this.setCommandMode=function(){g="command";A();h=setTimeout(r,0)};this.canUndo=function(){return 1<d};this.canRedo=function(){return b[d+1]?!0:!1};
this.undo=function(){c.canUndo()&&(k?(k.restore(),k=null):(b[d]=new t(e),b[--d].restore(),a&&a()));g="none";e.input.focus();r()};this.redo=function(){c.canRedo()&&(b[++d].restore(),a&&a());g="none";e.input.focus();r()};var A=function(){var c=D||new t(e);if(!c)return!1;"moving"==g?k||(k=c):(k&&(b[d-1].text!=k.text&&(b[d++]=k),k=null),b[d++]=c,b[d+1]=null,a&&a())},z=function(a){var b=!1;if((a.ctrlKey||a.metaKey)&&!a.altKey)switch(String.fromCharCode(a.charCode||a.keyCode).toLowerCase()){case "y":c.redo();
b=!0;break;case "z":a.shiftKey?c.redo():c.undo(),b=!0}b&&(a.preventDefault&&a.preventDefault(),window.event&&(window.event.returnValue=!1))},i=function(a){!a.ctrlKey&&!a.metaKey&&(a=a.keyCode,33<=a&&40>=a||63232<=a&&63235>=a?l("moving"):8==a||46==a||127==a?l("deleting"):13==a?l("newlines"):27==a?l("escape"):(16>a||20<a)&&91!=a&&l("typing"))};(function(){j.addEvent(e.input,"keypress",function(a){(a.ctrlKey||a.metaKey)&&!a.altKey&&(89==a.keyCode||90==a.keyCode)&&a.preventDefault()});var a=function(){if((m||
D&&D.text!=e.input.value)&&void 0==h)g="paste",A(),r()};j.addEvent(e.input,"keydown",z);j.addEvent(e.input,"keydown",i);j.addEvent(e.input,"mousedown",function(){l("moving")});e.input.onpaste=a;e.input.ondrop=a})();r(!0);A()}function t(a,e){var c=this,b=a.input;this.init=function(){if(j.isVisible(b)&&(e||!(i.activeElement&&i.activeElement!==b)))if(this.setInputAreaSelectionStartEnd(),this.scrollTop=b.scrollTop,!this.text&&b.selectionStart||0===b.selectionStart)this.text=b.value};this.setInputAreaSelection=
function(){if(j.isVisible(b))if(void 0!==b.selectionStart&&!x)b.focus(),b.selectionStart=c.start,b.selectionEnd=c.end,b.scrollTop=c.scrollTop;else if(i.selection&&!(i.activeElement&&i.activeElement!==b)){b.focus();var a=b.createTextRange();a.moveStart("character",-b.value.length);a.moveEnd("character",-b.value.length);a.moveEnd("character",c.end);a.moveStart("character",c.start);a.select()}};this.setInputAreaSelectionStartEnd=function(){if(!a.ieCachedRange&&(b.selectionStart||0===b.selectionStart))c.start=
b.selectionStart,c.end=b.selectionEnd;else if(i.selection){c.text=j.fixEolChars(b.value);var d=a.ieCachedRange||i.selection.createRange(),e=j.fixEolChars(d.text),k="\u0007"+e+"\u0007";d.text=k;var h=j.fixEolChars(b.value);d.moveStart("character",-k.length);d.text=e;c.start=h.indexOf("\u0007");c.end=h.lastIndexOf("\u0007")-1;if(k=c.text.length-j.fixEolChars(b.value).length){for(d.moveStart("character",-e.length);k--;)e+="\n",c.end+=1;d.text=e}a.ieCachedRange&&(c.scrollTop=a.ieCachedScrollTop);a.ieCachedRange=
null;this.setInputAreaSelection()}};this.restore=function(){void 0!=c.text&&c.text!=b.value&&(b.value=c.text);this.setInputAreaSelection();b.scrollTop=c.scrollTop};this.getChunks=function(){var a=new u;a.before=j.fixEolChars(c.text.substring(0,c.start));a.startTag="";a.selection=j.fixEolChars(c.text.substring(c.start,c.end));a.endTag="";a.after=j.fixEolChars(c.text.substring(c.end));a.scrollTop=c.scrollTop;return a};this.setChunks=function(a){a.before+=a.startTag;a.after=a.endTag+a.after;this.start=
a.before.length;this.end=a.before.length+a.selection.length;this.text=a.before+a.selection+a.after;this.scrollTop=a.scrollTop};this.init()}function s(a,e,c){var b,d,g,k=function(){var a=0;window.innerHeight?a=window.pageYOffset:i.documentElement&&i.documentElement.scrollTop?a=i.documentElement.scrollTop:i.body&&(a=i.body.scrollTop);return a},h=function(){if(e.preview){var b=e.input.value;if(!(b&&b==g)){g=b;var c=(new Date).getTime(),b=a.makeHtml(b);d=(new Date).getTime()-c;G(b)}}},D=function(){b&&
(clearTimeout(b),b=void 0);var a=0,a=d;3E3<a&&(a=3E3);b=setTimeout(h,a)};this.refresh=function(a){a?(g="",h()):D()};this.processingTime=function(){return d};var l=!0,r=function(a){var b=e.preview,d=b.parentNode,c=b.nextSibling;d.removeChild(b);b.innerHTML=a;c?d.insertBefore(b,c):d.appendChild(b)},A=function(a){e.preview.innerHTML=a},z,F=function(a){if(z)return z(a);try{A(a),z=A}catch(b){z=r,z(a)}},G=function(a){var b=p.getTop(e.input)-k();e.preview&&(F(a),c());e.preview&&(e.preview.scrollTop=(e.preview.scrollHeight-
e.preview.clientHeight)*(e.preview.scrollHeight<=e.preview.clientHeight?1:e.preview.scrollTop/(e.preview.scrollHeight-e.preview.clientHeight)));if(l)l=!1;else{var d=p.getTop(e.input)-k();m?setTimeout(function(){window.scrollBy(0,d-b)},0):window.scrollBy(0,d-b)}};(function(a,b){j.addEvent(a,"input",b);a.onpaste=b;a.ondrop=b;j.addEvent(a,"keypress",b);j.addEvent(a,"keydown",b)})(e.input,D);h();e.preview&&(e.preview.scrollTop=0)}function o(a,e,c,b,d,g,k){var h,D,l,r,A,z,F,G,v,p,n,o;function f(a){y.focus();
if(a.textOp){c&&c.setCommandMode();var d=new t(e);if(!d)return;var l=d.getChunks(),r=function(){y.focus();l&&d.setChunks(l);d.restore();b.refresh()};a.textOp(l,r)||r()}a.execute&&a.execute(c)}function s(a,b){var d=a.getElementsByTagName("span")[0];b?(d.style.backgroundPosition=a.XShift+" 0px",a.onmouseover=function(){d.style.backgroundPosition=this.XShift+" -40px"},a.onmouseout=function(){d.style.backgroundPosition=this.XShift+" 0px"},m&&(a.onmousedown=function(){i.activeElement&&i.activeElement!==
e.input||(e.ieCachedRange=document.selection.createRange(),e.ieCachedScrollTop=e.input.scrollTop)}),a.isHelp||(a.onclick=function(){if(this.onmouseout)this.onmouseout();f(this);return!1})):(d.style.backgroundPosition=a.XShift+" -20px",a.onmouseover=a.onmouseout=a.onclick=function(){})}function q(a){"string"===typeof a&&(a=d[a]);return function(){a.apply(d,arguments)}}function u(){c&&(s(n,c.canUndo()),s(o,c.canRedo()))}var y=e.input;h=void 0;D=void 0;l=void 0;r=void 0;A=void 0;z=void 0;F=void 0;G=
void 0;v=void 0;p=void 0;n=void 0;o=void 0;(function(){var b=e.buttonBar,d=document.createElement("ul");d.id="wmd-button-row"+a;d.className="wmd-button-row";var d=b.appendChild(d),c=0,b=function(b,e,l,r){var g=document.createElement("li");g.className="wmd-button";g.style.left=c+"px";c+=25;var k=document.createElement("span");g.id=b+a;g.appendChild(k);g.title=e;g.XShift=l;r&&(g.textOp=r);s(g,!0);d.appendChild(g);return g},i=function(b){var e=document.createElement("li");e.className="wmd-spacer wmd-spacer"+
b;e.id="wmd-spacer"+b+a;d.appendChild(e);c+=25};h=b("wmd-bold-button",k("bold"),"0px",q("doBold"));D=b("wmd-italic-button",k("italic"),"-20px",q("doItalic"));i(1);l=b("wmd-link-button",k("link"),"-40px",q(function(a,b){return this.doLinkOrImage(a,b,!1)}));r=b("wmd-quote-button",k("quote"),"-60px",q("doBlockquote"));A=b("wmd-code-button",k("code"),"-80px",q("doCode"));z=b("wmd-image-button",k("image"),"-100px",q(function(a,b){return this.doLinkOrImage(a,b,!0)}));i(2);F=b("wmd-olist-button",k("olist"),
"-120px",q(function(a,b){this.doList(a,b,!0)}));G=b("wmd-ulist-button",k("ulist"),"-140px",q(function(a,b){this.doList(a,b,!1)}));v=b("wmd-heading-button",k("heading"),"-160px",q("doHeading"));p=b("wmd-hr-button",k("hr"),"-180px",q("doHorizontalRule"));i(3);n=b("wmd-undo-button",k("undo"),"-200px",null);n.execute=function(a){a&&a.undo()};i=/win/.test(E.platform.toLowerCase())?k("redo"):k("redomac");o=b("wmd-redo-button",i,"-220px",null);o.execute=function(a){a&&a.redo()};g&&(b=document.createElement("li"),
i=document.createElement("span"),b.appendChild(i),b.className="wmd-button wmd-help-button",b.id="wmd-help-button"+a,b.XShift="-240px",b.isHelp=!0,b.style.right="0px",b.title=k("help"),b.onclick=g.handler,s(b,!0),d.appendChild(b));u()})();var w="keydown";x&&(w="keypress");j.addEvent(y,w,function(a){if((a.ctrlKey||a.metaKey)&&!a.altKey&&!a.shiftKey){switch(String.fromCharCode(a.charCode||a.keyCode).toLowerCase()){case "b":f(h);break;case "i":f(D);break;case "l":f(l);break;case "q":f(r);break;case "k":f(A);
break;case "g":f(z);break;case "o":f(F);break;case "u":f(G);break;case "h":f(v);break;case "r":f(p);break;case "y":f(o);break;case "z":a.shiftKey?f(o):f(n);break;default:return}a.preventDefault&&a.preventDefault();window.event&&(window.event.returnValue=!1)}});j.addEvent(y,"keyup",function(a){if(a.shiftKey&&!a.ctrlKey&&!a.metaKey&&13===(a.charCode||a.keyCode))a={},a.textOp=q("doAutoindent"),f(a)});m&&j.addEvent(y,"keydown",function(a){if(27===a.keyCode)return!1});this.setUndoRedoButtonStates=u}function C(a,
e){this.hooks=a;this.getString=e}function y(a){return a.replace(/^\s*(.*?)(?:\s+"(.+)")?\s*$/,function(a,c,b){c=c.replace(/\?.*$/,function(a){return a.replace(/\+/g," ")});c=decodeURIComponent(c);c=encodeURI(c).replace(/'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29");c=c.replace(/\?.*$/,function(a){return a.replace(/\+/g,"%2b")});b&&(b=b.trim?b.trim():b.replace(/^\s*/,"").replace(/\s*$/,""),b=b.replace(/"/g,"quot;").replace(/\(/g,"&#40;").replace(/\)/g,"&#41;").replace(/</g,"&lt;").replace(/>/g,
"&gt;"));return b?c+' "'+b+'"':c})}var j={},p={},B={},i=window.document,w=window.RegExp,E=window.navigator;m=/msie/.test(E.userAgent.toLowerCase());q=/msie 6/.test(E.userAgent.toLowerCase())||/msie 5/.test(E.userAgent.toLowerCase());x=/opera/.test(E.userAgent.toLowerCase());var h={bold:"Strong <strong> Ctrl+B",boldexample:"strong text",italic:"Emphasis <em> Ctrl+I",italicexample:"emphasized text",link:"Hyperlink <a> Ctrl+L",linkdescription:"enter link description here",linkdialog:'<p><b>Insert Hyperlink</b></p><p>http://example.com/ "optional title"</p>',
quote:"Blockquote <blockquote> Ctrl+Q",quoteexample:"Blockquote",code:"Code Sample <pre><code> Ctrl+K",codeexample:"enter code here",image:"Image <img> Ctrl+G",imagedescription:"enter image description here",imagedialog:"<p><b>Insert Image</b></p><p>http://example.com/images/diagram.jpg \"optional title\"<br><br>Need <a href='http://www.google.com/search?q=free+image+hosting' target='_blank'>free image hosting?</a></p>",olist:"Numbered List <ol> Ctrl+O",ulist:"Bulleted List <ul> Ctrl+U",litem:"List item",
heading:"Heading <h1>/<h2> Ctrl+H",headingexample:"Heading",hr:"Horizontal Rule <hr> Ctrl+R",undo:"Undo - Ctrl+Z",redo:"Redo - Ctrl+Y",redomac:"Redo - Ctrl+Shift+Z",help:"Markdown Editing Help"};Markdown.Editor=function(a,e,c){c=c||{};"function"===typeof c.handler&&(c={helpButton:c});c.strings=c.strings||{};c.helpButton&&(c.strings.help=c.strings.help||c.helpButton.title);var b=function(a){return c.strings[a]||h[a]},e=e||"",d=this.hooks=new Markdown.HookCollection;d.addNoop("onPreviewRefresh");d.addNoop("postBlockquoteCreation");
d.addFalse("insertImageDialog");this.getConverter=function(){return a};var g=this,k;this.run=function(){if(!k){k=new f(e);var h=new C(d,b),D=new s(a,k,function(){d.onPreviewRefresh()}),l,r;/\?noundo/.test(i.location.href)||(l=new n(function(){D.refresh();r&&r.setUndoRedoButtonStates()},k),this.textOperation=function(a){l.setCommandMode();a();g.refreshPreview()});r=new o(e,k,l,D,h,c.helpButton,b);r.setUndoRedoButtonStates();(g.refreshPreview=function(){D.refresh(!0)})()}}};u.prototype.findTags=function(a,
e){var c=this,b;a&&(b=j.extendRegExp(a,"","$"),this.before=this.before.replace(b,function(a){c.startTag+=a;return""}),b=j.extendRegExp(a,"^",""),this.selection=this.selection.replace(b,function(a){c.startTag+=a;return""}));e&&(b=j.extendRegExp(e,"","$"),this.selection=this.selection.replace(b,function(a){c.endTag=a+c.endTag;return""}),b=j.extendRegExp(e,"^",""),this.after=this.after.replace(b,function(a){c.endTag=a+c.endTag;return""}))};u.prototype.trimWhitespace=function(a){var e,c=this;a?a=e="":
(a=function(a){c.before+=a;return""},e=function(a){c.after=a+c.after;return""});this.selection=this.selection.replace(/^(\s*)/,a).replace(/(\s*)$/,e)};u.prototype.skipLines=function(a,e,c){void 0===a&&(a=1);void 0===e&&(e=1);a++;e++;var b,d;navigator.userAgent.match(/Chrome/)&&"X".match(/()./);this.selection=this.selection.replace(/(^\n*)/,"");this.startTag+=w.$1;this.selection=this.selection.replace(/(\n*$)/,"");this.endTag+=w.$1;this.startTag=this.startTag.replace(/(^\n*)/,"");this.before+=w.$1;
this.endTag=this.endTag.replace(/(\n*$)/,"");this.after+=w.$1;if(this.before){for(b=d="";a--;)b+="\\n?",d+="\n";c&&(b="\\n*");this.before=this.before.replace(new w(b+"$",""),d)}if(this.after){for(b=d="";e--;)b+="\\n?",d+="\n";c&&(b="\\n*");this.after=this.after.replace(new w(b,""),d)}};j.isVisible=function(a){if(window.getComputedStyle)return"none"!==window.getComputedStyle(a,null).getPropertyValue("display");if(a.currentStyle)return"none"!==a.currentStyle.display};j.addEvent=function(a,e,c){a.attachEvent?
a.attachEvent("on"+e,c):a.addEventListener(e,c,!1)};j.removeEvent=function(a,e,c){a.detachEvent?a.detachEvent("on"+e,c):a.removeEventListener(e,c,!1)};j.fixEolChars=function(a){a=a.replace(/\r\n/g,"\n");return a=a.replace(/\r/g,"\n")};j.extendRegExp=function(a,e,c){if(null===e||void 0===e)e="";if(null===c||void 0===c)c="";var a=a.toString(),b,a=a.replace(/\/([gim]*)$/,function(a,c){b=c;return""}),a=a.replace(/(^\/|\/$)/g,"");return new w(e+a+c,b)};p.getTop=function(a,e){var c=a.offsetTop;if(!e)for(;a=
a.offsetParent;)c+=a.offsetTop;return c};p.getHeight=function(a){return a.offsetHeight||a.scrollHeight};p.getWidth=function(a){return a.offsetWidth||a.scrollWidth};p.getPageSize=function(){var a,e,c,b;self.innerHeight&&self.scrollMaxY?(a=i.body.scrollWidth,e=self.innerHeight+self.scrollMaxY):i.body.scrollHeight>i.body.offsetHeight?(a=i.body.scrollWidth,e=i.body.scrollHeight):(a=i.body.offsetWidth,e=i.body.offsetHeight);self.innerHeight?(c=self.innerWidth,b=self.innerHeight):i.documentElement&&i.documentElement.clientHeight?
(c=i.documentElement.clientWidth,b=i.documentElement.clientHeight):i.body&&(c=i.body.clientWidth,b=i.body.clientHeight);a=Math.max(a,c);e=Math.max(e,b);return[a,e,c,b]};B.createBackground=function(){var a=i.createElement("div"),e=a.style;a.className="wmd-prompt-background";e.position="absolute";e.top="0";e.zIndex="1000";m?e.filter="alpha(opacity=50)":e.opacity="0.5";var c=p.getPageSize();e.height=c[1]+"px";m?(e.left=i.documentElement.scrollLeft,e.width=i.documentElement.clientWidth):(e.left="0",e.width=
"100%");i.body.appendChild(a);return a};B.prompt=function(a,e,c){var b,d;void 0===e&&(e="");var g=function(a){27===(a.charCode||a.keyCode)&&k(!0)},k=function(a){j.removeEvent(i.body,"keydown",g);var e=d.value;a?e=null:(e=e.replace(/^http:\/\/(https?|ftp):\/\//,"$1://"),/^(?:https?|ftp):\/\//.test(e)||(e="http://"+e));b.parentNode.removeChild(b);c(e);return!1},h=function(){b=i.createElement("div");b.className="wmd-prompt-dialog";b.style.padding="10px;";b.style.position="fixed";b.style.width="400px";
b.style.zIndex="1001";var c=i.createElement("div");c.innerHTML=a;c.style.padding="5px";b.appendChild(c);var c=i.createElement("form"),l=c.style;c.onsubmit=function(){return k(!1)};l.padding="0";l.margin="0";l.cssFloat="left";l.width="100%";l.textAlign="center";l.position="relative";b.appendChild(c);d=i.createElement("input");d.type="text";d.value=e;l=d.style;l.display="block";l.width="80%";l.marginLeft=l.marginRight="auto";c.appendChild(d);var r=i.createElement("input");r.type="button";r.onclick=
function(){return k(!1)};r.value="OK";l=r.style;l.margin="10px";l.display="inline";l.width="7em";var h=i.createElement("input");h.type="button";h.onclick=function(){return k(!0)};h.value="Cancel";l=h.style;l.margin="10px";l.display="inline";l.width="7em";c.appendChild(r);c.appendChild(h);j.addEvent(i.body,"keydown",g);b.style.top="50%";b.style.left="50%";b.style.display="block";q&&(b.style.position="absolute",b.style.top=i.documentElement.scrollTop+200+"px",b.style.left="50%");i.body.appendChild(b);
b.style.marginTop=-(p.getHeight(b)/2)+"px";b.style.marginLeft=-(p.getWidth(b)/2)+"px"};setTimeout(function(){h();var a=e.length;if(void 0!==d.selectionStart)d.selectionStart=0,d.selectionEnd=a;else if(d.createTextRange){var b=d.createTextRange();b.collapse(!1);b.moveStart("character",-a);b.moveEnd("character",a);b.select()}d.focus()},0)};var v=C.prototype;v.prefixes="(?:\\s{4,}|\\s*>|\\s*-\\s+|\\s*\\d+\\.|=|\\+|-|_|\\*|#|\\s*\\[[^\n]]+\\]:)";v.unwrap=function(a){var e=new w("([^\\n])\\n(?!(\\n|"+
this.prefixes+"))","g");a.selection=a.selection.replace(e,"$1 $2")};v.wrap=function(a,e){this.unwrap(a);var c=new w("(.{1,"+e+"})( +|$\\n?)","gm"),b=this;a.selection=a.selection.replace(c,function(a,c){return(new w("^"+b.prefixes,"")).test(a)?a:c+"\n"});a.selection=a.selection.replace(/\s+$/,"")};v.doBold=function(a,e){return this.doBorI(a,e,2,this.getString("boldexample"))};v.doItalic=function(a,e){return this.doBorI(a,e,1,this.getString("italicexample"))};v.doBorI=function(a,e,c,b){a.trimWhitespace();
a.selection=a.selection.replace(/\n{2,}/g,"\n");var d=/(\**$)/.exec(a.before)[0],e=/(^\**)/.exec(a.after)[0],d=Math.min(d.length,e.length);d>=c&&(2!=d||1!=c)?(a.before=a.before.replace(w("[*]{"+c+"}$",""),""),a.after=a.after.replace(w("^[*]{"+c+"}",""),"")):!a.selection&&e?(a.after=a.after.replace(/^([*_]*)/,""),a.before=a.before.replace(/(\s?)$/,""),a.before=a.before+e+w.$1):(!a.selection&&!e&&(a.selection=b),c=1>=c?"*":"**",a.before+=c,a.after=c+a.after)};v.stripLinkDefs=function(a,e){return a=
a.replace(/^[ ]{0,3}\[(\d+)\]:[ \t]*\n?[ \t]*<?(\S+?)>?[ \t]*\n?[ \t]*(?:(\n*)["(](.+?)[")][ \t]*)?(?:\n+|$)/gm,function(a,b,d,g,k){e[b]=a.replace(/\s*$/,"");return g?(e[b]=a.replace(/["(](.+?)[")]$/,""),g+k):""})};v.addLinkDef=function(a,e){var c=0,b={};a.before=this.stripLinkDefs(a.before,b);a.selection=this.stripLinkDefs(a.selection,b);a.after=this.stripLinkDefs(a.after,b);var d="",g=/(\[)((?:\[[^\]]*\]|[^\[\]])*)(\][ ]?(?:\n[ ]*)?\[)(\d+)(\])/g,k=function(a){c++;a=a.replace(/^[ ]{0,3}\[(\d+)\]:/,
"  ["+c+"]:");d+="\n"+a},h=function(a,d,e,i,f,j){e=e.replace(g,h);return b[f]?(k(b[f]),d+e+i+c+j):a};a.before=a.before.replace(g,h);e?k(e):a.selection=a.selection.replace(g,h);var i=c;a.after=a.after.replace(g,h);a.after&&(a.after=a.after.replace(/\n*$/,""));a.after||(a.selection=a.selection.replace(/\n*$/,""));a.after+="\n\n"+d;return i};v.doLinkOrImage=function(a,e,c){a.trimWhitespace();a.findTags(/\s*!?\[/,/\][ ]?(?:\n[ ]*)?(\[.*?\])?/);var b;if(1<a.endTag.length&&0<a.startTag.length)a.startTag=
a.startTag.replace(/!?\[/,""),a.endTag="",this.addLinkDef(a,null);else if(a.selection=a.startTag+a.selection+a.endTag,a.startTag=a.endTag="",/\n\n/.test(a.selection))this.addLinkDef(a,null);else{var d=this,g=function(g){b.parentNode.removeChild(b);null!==g&&(a.selection=(" "+a.selection).replace(/([^\\](?:\\\\)*)(?=[[\]])/g,"$1\\").substr(1),g=" [999]: "+y(g),g=d.addLinkDef(a,g),a.startTag=c?"![":"[",a.endTag="]["+g+"]",a.selection||(a.selection=c?d.getString("imagedescription"):d.getString("linkdescription")));
e()};b=B.createBackground();c?this.hooks.insertImageDialog(g)||B.prompt(this.getString("imagedialog"),"http://",g):B.prompt(this.getString("linkdialog"),"http://",g);return!0}};v.doAutoindent=function(a){var e=!1;a.before=a.before.replace(/(\n|^)[ ]{0,3}([*+-]|\d+[.])[ \t]*\n$/,"\n\n");a.before=a.before.replace(/(\n|^)[ ]{0,3}>[ \t]*\n$/,"\n\n");a.before=a.before.replace(/(\n|^)[ \t]+\n$/,"\n\n");!a.selection&&!/^[ \t]*(?:\n|$)/.test(a.after)&&(a.after=a.after.replace(/^[^\n]*/,function(c){a.selection=
c;return""}),e=!0);/(\n|^)[ ]{0,3}([*+-]|\d+[.])[ \t]+.*\n$/.test(a.before)&&this.doList&&this.doList(a);/(\n|^)[ ]{0,3}>[ \t]+.*\n$/.test(a.before)&&this.doBlockquote&&this.doBlockquote(a);/(\n|^)(\t|[ ]{4,}).*\n$/.test(a.before)&&this.doCode&&this.doCode(a);e&&(a.after=a.selection+a.after,a.selection="")};v.doBlockquote=function(a){a.selection=a.selection.replace(/^(\n*)([^\r]+?)(\n*)$/,function(b,d,c,e){a.before+=d;a.after=e+a.after;return c});a.before=a.before.replace(/(>[ \t]*)$/,function(b,
d){a.selection=d+a.selection;return""});a.selection=a.selection.replace(/^(\s|>)+$/,"");a.selection=a.selection||this.getString("quoteexample");var e="",c="",b;if(a.before){for(var d=a.before.replace(/\n$/,"").split("\n"),g=!1,k=0;k<d.length;k++){var h=!1;b=d[k];g=g&&0<b.length;/^>/.test(b)?(h=!0,!g&&1<b.length&&(g=!0)):h=/^[ \t]*$/.test(b)?!0:g;h?e+=b+"\n":(c+=e+b,e="\n")}/(^|\n)>/.test(e)||(c+=e,e="")}a.startTag=e;a.before=c;a.after&&(a.after=a.after.replace(/^\n?/,"\n"));a.after=a.after.replace(/^(((\n|^)(\n[ \t]*)*>(.+\n)*.*)+(\n[ \t]*)*)/,
function(b){a.endTag=b;return""});e=function(b){var d=b?"> ":"";a.startTag&&(a.startTag=a.startTag.replace(/\n((>|\s)*)\n$/,function(a,b){return"\n"+b.replace(/^[ ]{0,3}>?[ \t]*$/gm,d)+"\n"}));a.endTag&&(a.endTag=a.endTag.replace(/^\n((>|\s)*)\n/,function(a,b){return"\n"+b.replace(/^[ ]{0,3}>?[ \t]*$/gm,d)+"\n"}))};/^(?![ ]{0,3}>)/m.test(a.selection)?(this.wrap(a,70),a.selection=a.selection.replace(/^/gm,"> "),e(!0),a.skipLines()):(a.selection=a.selection.replace(/^[ ]{0,3}> ?/gm,""),this.unwrap(a),
e(!1),!/^(\n|^)[ ]{0,3}>/.test(a.selection)&&a.startTag&&(a.startTag=a.startTag.replace(/\n{0,2}$/,"\n\n")),!/(\n|^)[ ]{0,3}>.*$/.test(a.selection)&&a.endTag&&(a.endTag=a.endTag.replace(/^\n{0,2}/,"\n\n")));a.selection=this.hooks.postBlockquoteCreation(a.selection);/\n/.test(a.selection)||(a.selection=a.selection.replace(/^(> *)/,function(b,d){a.startTag+=d;return""}))};v.doCode=function(a){var e=/\S[ ]*$/.test(a.before);if(!/^[ ]*\S/.test(a.after)&&!e||/\n/.test(a.selection)){a.before=a.before.replace(/[ ]{4}$/,
function(b){a.selection=b+a.selection;return""});var c=e=1;/(\n|^)(\t|[ ]{4,}).*\n$/.test(a.before)&&(e=0);/^\n(\t|[ ]{4,})/.test(a.after)&&(c=0);a.skipLines(e,c);a.selection?/^[ ]{0,3}\S/m.test(a.selection)?/\n/.test(a.selection)?a.selection=a.selection.replace(/^/gm,"    "):a.before+="    ":a.selection=a.selection.replace(/^(?:[ ]{4}|[ ]{0,3}\t)/gm,""):(a.startTag="    ",a.selection=this.getString("codeexample"))}else a.trimWhitespace(),a.findTags(/`/,/`/),!a.startTag&&!a.endTag?(a.startTag=a.endTag=
"`",a.selection||(a.selection=this.getString("codeexample"))):a.endTag&&!a.startTag?(a.before+=a.endTag,a.endTag=""):a.startTag=a.endTag=""};v.doList=function(a,e,c){var e=/^\n*(([ ]{0,3}([*+-]|\d+[.])[ \t]+.*)(\n.+|\n{2,}([*+-].*|\d+[.])[ \t]+.*|\n{2,}[ \t]+\S.*)*)\n*/,b="-",d=1,g=function(){var a;c?(a=" "+d+". ",d++):a=" "+b+" ";return a},k=function(a){void 0===c&&(c=/^\s*\d/.test(a));return a=a.replace(/^[ ]{0,3}([*+-]|\d+[.])\s/gm,function(){return g()})};a.findTags(/(\n|^)*[ ]{0,3}([*+-]|\d+[.])\s+/,
null);a.before&&!/\n$/.test(a.before)&&!/^\n/.test(a.startTag)&&(a.before+=a.startTag,a.startTag="");if(a.startTag){var h=/\d+[.]/.test(a.startTag);a.startTag="";a.selection=a.selection.replace(/\n[ ]{4}/g,"\n");this.unwrap(a);a.skipLines();h&&(a.after=a.after.replace(e,k));if(c==h)return}var i=1;a.before=a.before.replace(/(\n|^)(([ ]{0,3}([*+-]|\d+[.])[ \t]+.*)(\n.+|\n{2,}([*+-].*|\d+[.])[ \t]+.*|\n{2,}[ \t]+\S.*)*)\n*$/,function(a){/^\s*([*+-])/.test(a)&&(b=w.$1);i=/[^\n]\n\n[^\n]/.test(a)?1:0;
return k(a)});a.selection||(a.selection=this.getString("litem"));var h=g(),l=1;a.after=a.after.replace(e,function(a){l=/[^\n]\n\n[^\n]/.test(a)?1:0;return k(a)});a.trimWhitespace(!0);a.skipLines(i,l,!0);a.startTag=h;e=h.replace(/./g," ");this.wrap(a,72-e.length);a.selection=a.selection.replace(/\n/g,"\n"+e)};v.doHeading=function(a){a.selection=a.selection.replace(/\s+/g," ");a.selection=a.selection.replace(/(^\s+|\s+$)/g,"");if(a.selection){var e=0;a.findTags(/#+[ ]*/,/[ ]*#+/);/#+/.test(a.startTag)&&
(e=w.lastMatch.length);a.startTag=a.endTag="";a.findTags(null,/\s?(-+|=+)/);/=+/.test(a.endTag)&&(e=1);/-+/.test(a.endTag)&&(e=2);a.startTag=a.endTag="";a.skipLines(1,1);e=0==e?2:e-1;if(0<e){var e=2<=e?"-":"=",c=a.selection.length;72<c&&(c=72);for(a.endTag="\n";c--;)a.endTag+=e}}else a.startTag="## ",a.selection=this.getString("headingexample"),a.endTag=" ##"};v.doHorizontalRule=function(a){a.startTag="----------\n";a.selection="";a.skipLines(2,1,!0)}})();
(function(){function m(){for(var a=0;a<w.length;a++)w[a].refreshPreview()}function x(a){var b=a.match(/^\s*>\s*!/mg);if(b&&b.length==a.split("\n").length){var d=!1,a=a.replace(/(.*) (\w)/,function(a,b,c){d=!0;return b+"\n> "+c});d||(a=a.replace(/^(\s*>\s*)!/m,"$1&#33;"))}return a}function q(a){var b=/^\s*?[^\s!]/m,d=/^\s*?!/gm;return a=a.replace(/\<blockquote\>[\n\s]*?\<p\>[\n\s]*?(![\s\S]*?)\<\/p\>[\n\s]*?\<\/blockquote\>/g,function(a,c){if(b.test(c))return a;a=a.replace(c,c.replace(d,""));return a=
a.replace("<blockquote>",'<blockquote class="spoiler">')})}function u(a){if(!window.tagRendererRaw)return a;var b,d;return a=a.replace(/\[(meta-)?tag:([a-z0-9#+.-]+)\]/gi,function(c,e,g,k){if(!i&&e)return c;if(!b){for(var h=a,f=[],j=/<(a|code)[^>]*>/ig,o;null!=(o=j.exec(h));){f.push(o.index);o=RegExp("</"+o[1]+">","ig");o.lastIndex=j.lastIndex;if(null==o.exec(h))break;f.push(o.lastIndex);j.lastIndex=o.lastIndex}b=f;d=b.length}h=!1;for(f=0;f<d&&!(b[f]>k);f++)h=!h;if(h)return c;c=null;i&&!e&&(c=B);
return tagRendererRaw(sanitizeAndSplitTags(g)[0],c)})}function f(a){var b,d;"undefined"==typeof v&&(v=StackExchange.options.styleCode);v&&(b=o(a),d=o(b+a),a=y(a,b,d));a=n(a);v&&(a=j(a,b,d));return a}function n(a){return a.replace(/<[^>]*>?/gi,t)}function t(b){return b.match(a)||b.match(e)||b.match(c)?b:""}function s(a){if(""==a)return"";var b=/<\/?\w+[^>]*(\s|$|>)/g,d=a.toLowerCase().match(b),c=(d||[]).length;if(0==c)return a;for(var e,g,h,k=[],i=[],f=!1,j=0;j<c;j++)if(e=d[j].replace(/<\/?(\w+).*/,
"$1"),!(k[j]||-1<"<p><img><br><li><hr>".search("<"+e+">"))){g=d[j];h=-1;if(!/^<\//.test(g))for(g=j+1;g<c;g++)if(!k[g]&&d[g]=="</"+e+">"){h=g;break}-1==h?f=i[j]=!0:k[h]=!0}if(!f)return a;j=0;return a=a.replace(b,function(a){a=i[j]?"":a;j++;return a})}function o(a){a=(a.match(/~/g)||[]).length;return Array(a+2).join("~")}function C(a){if(/^lang-/.test(a))return a;var c="c_"+a,e=b[c];if(e)return e;if(d[c])return null;d[c]=!0;c=g.length;0<c&&RegExp("^"+g[c-1]).test(a)?g[c-1]=a:g.push(a);k.trigger();return null}
function y(a,b,d){a=a.replace(I,function(a,d,c){return b+d+b+c});return a.replace(D,function(a,b){return d+b+d})}function j(a,b,d){var a=a.replace(RegExp(b+"([a-z0-9#+.-]+)"+b+"(\\s*?<pre)","gi"),function(a,b,d){a=C(b);return!a?d:d+" class='"+a+" prettyprint-override'"}),c;return a.replace(RegExp("("+d+"([a-z0-9#+.-]+)"+d+")|(<pre><code>)","gi"),function(a,b,d){if(b)return c=d,"";if(!c)return a;b=C(c);return!b?a:"<pre class='"+b+" prettyprint-override'><code>"})}function p(a){function b(){e.animate({height:g.height()-
h})}function d(a){if(g)a();else if(!j){j=!0;var c=o.offset();h=c.top-$("#wmd-button-row"+f).offset().top-$("#wmd-button-row"+f).outerHeight()-5;k=$("#wmd-help-button"+f);var l=k.offset().left+k.outerWidth(),c=c.left,n=o.outerWidth()+c,n=Math.max(l,n);i={right:l-n,width:n-c,top:$("#wmd-button-row"+f).outerHeight()+5};k.addClass("active-help");e=$("<div style='clear:both' />").insertBefore(o);g=$('<div id="mdhelp'+f+'" class="mdhelp"><ul id="mdhelp-tabs'+f+'" class="mdhelp-tabs"><li /></ul></div>').find("li").addSpinner().end().css(i).insertAfter(k);
b();$.get("/posts/markdown-help",{postfix:f}).done(function(d){g.remove();g=$(d).insertAfter(k).css(i);$("#mdhelp-tabs"+f).delegate("li:not(:last-child)","click",function(){var a=$(this).hasClass("selected");g.find(".mdhelp-tab").hide();$("#mdhelp-tabs"+f+" li").removeClass("selected");if(!a&&($("#"+$(this).attr("data-tab")).show(),$(this).addClass("selected"),a=$(this).attr("data-buttons")))for(var a=a.split(","),d=0;d<a.length;d++){var c=$("#wmd-"+a[d]+"-button"+f);c.is(":animated")||c.animate({top:-15},
400).animate({top:0},400).animate({top:-8},300).animate({top:0},300).animate({top:-4},200).animate({top:0},200).animate({top:-2},100).animate({top:0},100).animate({top:-1},50).animate({top:0},50)}b()});j=!1;a()})}}function c(){n=!0;d(function(){k.addClass("active-help");g.show();b()})}var e,g,h,k,i,j=!1,f=(a||{}).postfix||"",o=$("#wmd-input"+f),n=!1;this.toggle=function(){g&&g.is(":visible")?(g.hide(),e.animate({height:0}),k.removeClass("active-help")):c()};this.showOnce=function(){n||c()}}if(!StackExchange.MarkdownEditor){var B,
i,w=[],E=function(a){function b(a){return"facebook.stackoverflow.com"===a?"stackoverflow.com":a}function d(b){window.apiCallbacks[b]||(window.apiCallbacks[b]=function(d){if(d)if(d.error_message)/^No site found/.test(d.error_message)&&(o["s_"+b]=!0);else if(d.items){for(var d=d.items,c=d.length,e=0;e<c;e++){var g=d[e];h[b+"|"+g.question_id]=g.title}a&&a()}});return'apiCallbacks["'+b+'"]'}function c(a,d){if(b(a)===k)return!0;var e=n[a];e||(e=n[a]={count:0,ids:{}});if(e.ids[d])return!0;if(e.count>=v)return!1;
e.count++;return e.ids[d]=!0}var e=/<a href="((\S+)\/q(?:uestions)?\/(\d+)(?:|\/\S*?))">\1<\/a>/g,g=window.location.hostname.toLowerCase(),k=b(g),h={},f={},i={},j=StackExchange.helpers.DelayedReaction(function(){var a=!1,c;for(c in i)if(i.hasOwnProperty(c)){var e=d(c),g;30<i[c].length?g=i[c].splice(0,30).join(";"):(g=i[c].join(";"),delete i[c]);a=!0;$.ajax({url:"http://api.stackexchange.com/2.0/questions/"+g+"?pagesize=30&key=6AU78DZ)GcdjNjAszYmTLQ((&filter=!6G7RPxWUNTleV&site="+b(c),crossDomain:!0,
jsonpCallback:e,dataType:"jsonp"});break}a&&j.trigger()},1E3,{sliding:!0}),o={};window.apiCallbacks={};var n={},v=/^meta\./.test(k)?40:10;return function(a){n={};return a.replace(e,function(a,d,e,g){e=e.toLowerCase().replace(/^http:\/\//,"");if(/[^a-z0-9.]/.test(e)||!c(e,g))return a;var l=h[e+"|"+g];if(l)g=l;else{if(l=!f[e+"|"+g]){l=b(e);if(l===k)l=!1;else if(o["s_"+l])l=!0;else var n=/^meta\./.test(k),l=k==="meta."+l||!n&&"meta."+k===l||n&&"meta.stackoverflow.com"==l||"meta.stackoverflow.com"===
k?!1:!0;l=!l}l&&(f[e+"|"+g]=!0,(l=i[e])||(l=i[e]=[]),l.push(g),j.trigger());g=null}return!g?a:'<a href="'+d+'">'+g+"</a>"})}}(m),h=$.Callbacks();StackExchange.MarkdownEditor=function(a){var b=a.postfix||"";B=$("#hlinks a").filter(function(){return"main"==$(this).text()}).attr("href");i=!!B;var d=new Markdown.Converter,c=d.hooks;c.addNoop("preSafe");c.chain("postConversion",E);c.chain("postConversion",function(a){return c.preSafe(a)});c.chain("postConversion",f);c.chain("postConversion",s);c.chain("postConversion",
q);c.chain("postConversion",u);var e=new p({postfix:b}),g={helpButton:{handler:e.toggle}};a.noCode&&(g.strings={code:"Preformatted text <pre><code> Ctrl-K",codeexample:"enter preformatted text here"});d=new Markdown.Editor(d,b,g);d.hooks.chain("postBlockquoteCreation",x);StackExchange.options.disableImageUploads||d.hooks.set("insertImageDialog",StackExchange.imageUploader.uploadImageDialog);h.fire(d,a.postfix);var k=$("#wmd-preview"+b);d.hooks.chain("onPreviewRefresh",function(){k.trigger("wmdrefresh")});
w.push(d);d.run();if(a.immediatelyShowMarkdownHelp)e.showOnce(a);else if(a.autoShowMarkdownHelp)$("#wmd-input"+b).one("focus",function(){e.showOnce(a)});d.disableSubmission=function(){$("#submit-button"+b).attr("disabled","disabled");StackExchange.navPrevention.stop()};return d};StackExchange.MarkdownEditor.creationCallbacks=h;StackExchange.MarkdownEditor.refreshAllPreviews=m;var v;StackExchange.MarkdownEditor.sanitizeHtml=n;var a=/^(<\/?(b|blockquote|code|del|dd|dl|dt|em|h1|h2|h3|i|kbd|li|ol|p|pre|s|sup|sub|strong|strike|ul)>|<(br|hr)\s?\/?>)$/i,
e=/^(<a\shref="((https?|ftp):\/\/|\/)[-A-Za-z0-9+&@#\/%?=~_|!:,.;\(\)]+"(\stitle="[^"<>]+")?\s?>|<\/a>)$/i,c=/^(<img\ssrc="(https?:\/\/|\/)[-A-Za-z0-9+&@#\/%?=~_|!:,.;\(\)]+"(\swidth="\d{1,3}")?(\sheight="\d{1,3}")?(\salt="[^"<>]*")?(\stitle="[^"<>]*")?\s?\/?>)$/i;StackExchange.MarkdownEditor.balanceTags=s;var b={},d={},g=[],k=StackExchange.helpers.DelayedReaction(function(){0!=g.length&&($.ajax("/api/tags/"+encodeURIComponent(g.join(";"))+"/syntax-highlight",{cache:!0}).done(function(a){var d=!1,
c;for(c in a)a.hasOwnProperty(c)&&(b["c_"+c]=a[c],d=!0);d&&(StackExchange.MarkdownEditor.refreshAllPreviews(),styleCode())}),g=[])},2E3,{sliding:!0}),I=/<\!-- language: ([a-z0-9#+\-.]+) --\>(\s*?<pre>\s*?<code>)/gi,D=/<\!-- language-all: ([a-z0-9#+\-.]+) --\>/gi}})();
StackExchange.editor=function(){var m=function(m){var m=m||{},q=m.postfix||"",u=m.heartbeatType,f=m.bindNavPrevention,n=$("#post-form"+q),t=$("#wmd-input"+q),s;s=$("#title, #edit-comment, #m-address, .edit-comment");q=s.add(".tag-editor input");n.submit(function(){s.each(function(){StackExchange.helpers.hideHelpOverlay($(this))});StackExchange.helpers.disableSubmitButton(n);StackExchange.navPrevention.stop();return!0});$(".original-question").not(".processed").TextAreaResizer();t.not(".processed").TextAreaResizer();
t.typeWatch({highlight:!1,wait:5E3,captureLength:5,callback:styleCode});var o=new StackExchange.MarkdownEditor(m);if(u){var C=m.discardSelector?$(m.discardSelector):null;StackExchange.cardiologist.addHeart(u,t,o,C,m.postId)}if("ask"==u||"answer"==u){var y=t.add(q),j=function(){StackExchange.helpers.loadTicks(n);y.unbind("keydown",j);return!0};y.bind("keydown",j)}f&&StackExchange.navPrevention.init(t);n.find(".wmd-preview").click(function(){$(this).siblings().find("textarea").focus()});StackExchange.helpers.bindHelpOverlayEvents(s);
0==$("#ask-page-has-errors").length&&$("#title").is("input")&&$("#title").focus();if(m.oncreated)m.oncreated(o);if(m.discardSelector&&("ask"==u||"answer"==u||"moderatormessage"==u)){var p=$(m.discardSelector);p.click(function(f){f.preventDefault();if(confirm("Are you sure you want to discard your draft?"))return $("#title").val("").blur(),$("#question-suggestions").empty(),$("#wmd-input-42").val(""),$("#wmd-preview-42").html(""),$("#answer-from-ask").is(":visible")&&$("#answer-from-ask").is(":checked")&&
$("#answer-from-ask").click(),f=$("#tagnames"),0<f.length&&f[0].func_clear&&(f[0].func_clear(),f.blur()),t.val("").blur(),o.refreshPreview(),$.post("/post/discard-draft",{fkey:StackExchange.options.user.fkey,postType:u},function(){$("#draft-saved").hide();$("#draft-discarded").show();var f=null,f=function(){$("#draft-discarded").hide();$("#title").unbind("keypress",f);t.unbind("keypress",f)};$("#title").bind("keypress",f);t.bind("keypress",f)}),p.hide(),!1})}};return{init:m,initIfShown:function(x){var q=
(x||{}).postfix||"";0!=$("#wmd-preview"+q).length&&("-42"!==q||0===$("#answer-from-ask").length)&&0===$("#show-editor-button"+q).length?(m(x),StackExchange.editor.finallyInit||(StackExchange.editor.finallyInit=function(){})):StackExchange.editor.finallyInit=function(){m(x)}}}}();
StackExchange.cardiologist=function(){function m(h){h="number"===typeof h?h:1E3*(C+y);B&&(h=Math.max(h,6E3-((new Date).getTime()-B)));i&&clearTimeout(i);i=setTimeout(x,h)}function x(){i=null;if(!t.length){var h;t=[];n&&!n.isDisabled&&30>n.beatCount&&t.push(n);for(var j=0;j<f.length;j++)h=f[j],h!=n&&!h.isDisabled&&30>h.beatCount&&t.push(h);C=Math.max(15,Math.min(45,60/(t.length||1)))}t.length?(h=t.shift(),h.checkActive()?h.beat():m()):m()}function q(){}function u(h){var f=[];$.get("/questions/"+h,
function(a){a=$(a);a.find("div.answer").each(function(){var a=this.id.substring(7);0==$("#answer-"+a).length&&f.push(this.id)});if(0<f.length){var e="#"+f.join(",#"),a=a.find(e),e=$("div.answer:last");0==e.length&&(e=$("#answers-header"));a.hide();e.after(a);a.fadeIn("slow");e=$("div.answer").length;$(".subheader h2").text(e+" Answer"+(1<e?"s":""));StackExchange.vote.init(h);StackExchange.comments.init({post:a})}StackExchange.notify.close(p);j=!1},"html")}var f=[],n,t=[],s,o,C=45,y=0,j=!1,p=-2,B,
i,w={ask:function(h){if(h.relatedQuestions){var f=$("#how-to-format"),a=h.relatedQuestions!=o;a&&f.hide();f.empty().append("<h4>Similar Questions</h4>"+h.relatedQuestions);a&&showFadingHelpText(f);o=h.relatedQuestions}h.suggestedTags&&StackExchange.tagSuggestions&&StackExchange.tagSuggestions.suggest(h.suggestedTags)},answer:function(h,f){if(h&&!j)if(h.disableEditor)StackExchange.notify.show("This question has been "+h.message+" - no more answers will be accepted.",p),j=!0;else{var a=parseInt(h.message);
0<a&&(StackExchange.notify.show(a+" new answer"+(1==a?" has":"s have")+' been posted - <a id="load-new-answers">load new answers.</a>',p),j=!0,$("#load-new-answers").click(function(){u(f.postId)}))}},edit:function(h){h&&h.message&&StackExchange.notify.getMessageText(p)!=$("<span />").html(h.message).text()&&(StackExchange.notify.close(p),StackExchange.notify.show(h.message,p))},moderatormessage:function(){}};q.prototype={activate:function(){n=this;this.isActive||(this.isActive=!0,this.beatCount=0,
f.push(this),1===f.length&&m())},checkActive:function(){if(!this.isActive||this.isDisabled)return!1;return!this.jTextarea.closest("body").length?(delete this.jTextarea,this.isDisabled=!0,!1):!0},beat:function(h){var f=this,a={type:"POST",url:"/posts/"+this.postId+"/editor-heartbeat/"+this.type,dataType:"json",data:{}};h||(a.success=function(a){f.success(a)},a.error=function(){f.error()},a.complete=function(){f.complete()});if(this.shouldSendDraft()){var e={text:this.jTextarea.val()};"ask"===this.type&&
(e.title=$("#title").val(),e.tagnames=$("#tagnames").val(),e.answertext=$("#wmd-input-42").val());if(!s||s.heart!==this||s.title!==e.title||s.tagnames!==e.tagnames||s.text!==e.text||s.answertext!==e.answertext)a.data=e,s={heart:this,title:e.title,tagnames:e.tagnames,text:e.text,answertext:e.answertext}}if(h&&!("text"in a.data))return $.Deferred().resolve().promise();this.revisionGuid&&(a.data.clientRevisionGuid=this.revisionGuid);"answer"===this.type&&(h=$("#answers-header .answers-subheader h2").text().replace(/ answers?/i,
"")||"0",a.data.clientCount=h);B=(new Date).getTime();return $.ajax(a).promise()},shouldSendDraft:function(){return"edit"!==this.type&&n===this},success:function(h){w[this.type](h,this);h.disableEditor&&(this.editor.disableSubmission(),this.isDisabled=!0);h.draftSaved&&E(this.jTextarea,this.discardDraftLink);this.beatCount++;y=0},error:function(){$("#draft-saved").hide();n===this&&t.unshift(this);y=(new Date).getTime()%100/10},complete:function(){m()}};var E=function(h,f){var a=$("#draft-saved"),
e=function(){a.text("draft saved").fadeIn("fast")};a.is(":visible")?a.fadeOut("fast",e):e();f&&f.removeClass("dno").show();var c=function(a){if(115!=a.which||!a.ctrlKey||a.shiftKey||a.altKey)h.unbind("keypress",c),$("#draft-saved").fadeOut("fast")};h.bind("keypress",c);$("#draft-discarded").hide()};return{addHeart:function(h,f,a,e,c){var b=new q,d;b.type=h;b.jTextarea=f;b.discardDraftLink=e;switch(h){case "ask":d=0;break;case "answer":d=$("#post-id").val()||location.href.match(/\/questions\/(\d+)/i)[1];
break;case "edit":d=c||$("#post-id").val()||f.closest(".question, .answer").find(".vote input").val();h=f.closest(".inline-post");e=null;0<h.length&&(e=h[0].action.split("/").pop());e||(e=$("#client-revision-guid").val());b.revisionGuid=e;break;case "moderatormessage":d=+$("#moderator-message-to-user").attr("data-userid")}b.postId=d;b.editor=a;f.keypress(function(){b.activate()})},ensureDraftSaved:function(f,i){!n||!n.checkActive()?f():n.beat(i).done(f)},beatASAP:function(){m(1)},notifiedOfNewAnswer:function(){j=
!0},isHeartBeating:function(){if(null==f)return!1;for(var h=0;h<f.length;h++)if(!0==f[h].checkActive())return!0;return!1}}}();
StackExchange.navPrevention=function(){var m,x,q=function(){var f=!1;m.each(function(m){f=f||$(this).val()!==x[m]});return f},u=function(f){window.onbeforeunload=f?function(){if(m&&q())return f}:null},f=function(){u("You have started writing or editing a post.")};return{init:function(n){m=n.one("keypress",f);x=[];n.each(function(){x.push($(this).val())})},start:function(){m&&f()},stop:function(){m&&(m.unbind("keypress",f),u(null),m=null)},confirm:function(f){return m&&q()?confirm(f):!0}}}();
(function(m){function x(o){f=m(o.data.el);f.blur();t=o.clientY+document.documentElement.scrollTop;n=f.height()-t;f.css("opacity",0.25);m(document).mousemove(q).mouseup(u);return!1}function q(o){var m=o.clientY+document.documentElement.scrollTop,q=n+m;t>=m&&(q-=5);t=m;q=Math.max(s,q);f.height(q+"px");q<s&&u(o);return!1}function u(){m(document).unbind("mousemove",q).unbind("mouseup",u);f.css("opacity",1);f.focus();n=f=null;t=0}var f,n,t=0,s=32;m.fn.TextAreaResizer=function(){return this.each(function(){f=
m(this).addClass("processed");n=null;m(this).parent().append(m('<div class="grippie"></div>').bind("mousedown",{el:this},x));var o=m("div.grippie",m(this).parent())[0];o.style.marginRight=o.offsetWidth-m(this)[0].offsetWidth+"px"})}})(jQuery);"use strict";
StackExchange.imageUploader=function(){return{uploadImageDialog:function(m,x){var q="upload-iframe-"+(new Date).getTime();"undefined"===typeof x&&(x="/upload/image");var u="",f=window.FileReader&&window.FormData,n=f&&"ondrop"in window,t=f&&"onpaste"in document.body&&window.Clipboard;n&&t?u="(or paste or drag-and-drop)":n&&(u="(or drag-and-drop)");var s=$('<div class="popup" id="image-upload" style="z-index:1010; width: 420px;" tabindex="-1"><div class="popup-close"><a title="close this popup (or hit Esc)">&times;</a></div><iframe id="'+
q+'" style="display:none;" src="about:blank" name="'+q+'"/><form action="'+x+'" id="upload-form" method="post" enctype="multipart/form-data"><input type="hidden" name="fkey" value="'+StackExchange.options.user.fkey+'" /><div><h2 style="margin-bottom: 12px; cursor: move;" class="handle">Add Image</h2><input type="radio" name="source" id="computer" checked="checked" value="computer" /> <label for="computer">From my computer</label> <input type="file" name="filename" id="filename-input" value="browse" size="18" style="float: right; width: 250px;" /><div id="url-wrapper" style="float: right; border: 0; padding: 0; margin: 0; display: none;"><input type="text" name="upload-url" id="url-input" style="width: 250px;" /><span class="edit-field-overlay">http://example.com/image.png</span></div><br /><input type="radio" name="source" id="web" value="web" /> <label for="web">From the web</label><br /><br /><p id="upload-message" style="padding-top: 4px; margin:0; line-height: 16px;"></p><p>'+
u+'</p><p style="position: absolute; font-size: smaller; bottom: 10px; width: 313px;">user contributions licensed under<br/><a href="http://creativecommons.org/licenses/by-sa/3.0/">cc-wiki with attribution required</a>&nbsp;(<a href="http://stackexchange.com/legal/content-policy">content policy</a>)</p><input type="submit" id="add-picture" value="Add picture" style="float: right;" /></div></form></div><script type="text/javascript">    StackExchange.helpers.bindMovablePopups();    StackExchange.helpers.bindHelpOverlayEvents($("#url-input"));<\/script>'),
o,C,y,j=function(a){27===(a.charCode||a.keyCode)&&p(null)},p=function(a){s&&s.fadeOutAndRemove();$("body").unbind("keydown",j);$("body").unbind("paste");void 0!==a&&m(a);C&&C.fadeOutAndRemove();return!1},B=function(a){p();C=$('<div class="popup" id="image-upload" style="z-index:1010;"><iframe id="'+q+'" style="display:none;" src="about:blank" name="'+q+'"/><div class="popup-close"><a title="close this popup (or hit Esc)">&times;</a></div><input type="hidden" name="fkey" value="'+StackExchange.options.user.fkey+
'" /><div><h2 style="margin-bottom: 12px; cursor: move;" class="handle">Add a picture</h2><img src="'+a+'" style="max-width: 250px;padding: 5px;" /><br /><p id="upload-message" style="padding-top: 4px; margin:0; line-height: 16px;"><span style="float: right;"><input type="button" id="confirm-upload" value="Confirm" />&nbsp;&nbsp;&nbsp;<a id="cancel-upload">cancel</a></span></div></form></div>    <script type="text/javascript">    StackExchange.helpers.bindMovablePopups();<\/script>');e(C)},i=function(a){a=
a||window.event;a.preventDefault&&a.preventDefault();o.style.backgroundColor="white";y=a.dataTransfer.files[0];a=new window.FileReader;a.onloadend=w;a.readAsDataURL(y);return!1},w=function(a){B(a.target.result)},E=function(a){a=a.originalEvent||window.event;if(a.clipboardData&&(a=a.clipboardData.items))for(var b=0;b<a.length;b++)if(-1!==a[b].type.indexOf("image")){y=a[b].getAsFile();var d=(window.URL||window.webkitURL).createObjectURL(y);B(d)}},h=function(){return!1},v=function(){return!1},a=function(){C.find("#upload-message").text("Uploading ").addSpinner();
if(window.FormData){var a=new window.FormData;a.append("uploadedImage",y);a.append("fkey",StackExchange.options.user.fkey);$.ajax({url:x,data:a,cache:!1,contentType:!1,processData:!1,type:"POST",success:function(a){$("#"+q).contents().find("html").html(a)}})}},e=function(){C.appendTo("#header").center().fadeIn("fast");$("body").keydown(j);C.find(".popup-close").click(function(){p(null)});$("#cancel-upload").click(function(){p(null)});$("#confirm-upload").click(a);window.closeDialog=p;window.displayUploadError=
function(a){$("#upload-message").css({color:"red",fontWeight:"bold"}).show().text(a)}};s.appendTo("#header").center().fadeIn("fast").promise().done(function(){o=document.getElementById("image-upload");n&&(o.ondrop=i,o.ondragover=v,o.ondragleave=h);t&&$("body").bind("paste",E);s.find(".popup-close").click(function(){p(null)});s.find(":radio").change(function(){var a=s.find("#filename-input"),b=s.find("#url-wrapper");a.toggle();b.toggle();$("#upload-message").css({color:"inherit",fontWeight:"inherit"}).hide().text("");
b.is(":visible")&&s.find("#url-input").focus()});s.find("form").submit(function(){s.find("#upload-message").text("Uploading ").addSpinner();var a=s.find(":radio:checked").val(),b=s.find("#filename-input"),d=s.find("#url-wrapper"),e;if("web"==a){var f=b.next();b.detach();e=function(){b.insertBefore(f)}}else{var h=d.next();d.detach();e=function(){d.insertBefore(h)}}this.target=q;window.closeDialog=p;window.displayUploadError=function(a){$("#upload-message").css({color:"red",fontWeight:"bold"}).show().text(a);
e();e=null};return!0});s.find("#filename-input").focus()});$("body").keydown(j);return!0}}}();
StackExchange.postValidation=function(){function m(a,d,c){var e=a.find('input[type="submit"]:visible'),h=e.length&&e.is(":enabled");h&&e.attr("disabled",!0);q(a);u(a,d,c);n(a);t(a);s(a);var i=function(){1!=d||a.find(E).length?(f(a),h&&e.attr("disabled",!1)):setTimeout(i,250)};i()}function x(){for(var a=0;a<e.length;a++)clearTimeout(e[a]);e=[]}function q(a){var d=a.find(i);d.length&&d.blur(function(){e.push(setTimeout(function(){var c=d.val(),e=$.trim(c);if(0==e.length)p(a,d);else{var f=d.data("min-length");
f&&e.length<f?j(d,["Title must be at least "+f+" characters."],o()):(f=d.data("max-length"))&&e.length>f?j(d,["Title cannot be longer than "+f+" characters."],o()):$.ajax({type:"POST",url:"/posts/validate-title",data:{title:c},success:function(c){c.success?p(a,d):j(d,c.errors.Title,o())},error:function(){p(a,d)}})}},c))})}function u(a,d,g){var f=a.find(w);f.length&&f.blur(function(){e.push(setTimeout(function(){var c=f.val(),e=$.trim(c);0==e.length?p(a,f):5==d?(c=f.data("min-length"))&&e.length<c?
j(f,["Wiki Body must be at least "+c+" characters. You entered "+e.length+"."],o()):p(a,f):(1==d||2==d)&&$.ajax({type:"POST",url:"/posts/validate-body",data:{body:c,oldBody:f.prop("defaultValue"),isQuestion:1==d,isSuggestedEdit:g},success:function(d){d.success?p(a,f):j(f,d.errors.Body,o())},error:function(){p(a,f)}})},c))})}function f(a){var d=a.find(E);if(d.length){var g=d.parent().find("input#tagnames");g.blur(function(){e.push(setTimeout(function(){var c=g.val();0==$.trim(c).length?p(a,d):$.ajax({type:"POST",
url:"/posts/validate-tags",data:{tags:c,oldTags:g.prop("defaultValue")},success:function(c){c.success?p(a,d):d.parents(".post-taglist").is(":visible")&&!d.parents(".post-taglist").is(":animated")&&j(d,c.errors.Tags,o())},error:function(){p(a,d)}})},c))})}}function n(a){var d=a.find(h);d.length&&d.blur(function(){e.push(setTimeout(function(){var c=d.val(),c=$.trim(c);if(0==c.length)p(a,d);else{var e=d.data("min-length");e&&c.length<e?j(d,["Your edit summary must be at least "+e+" characters."],o()):
(e=d.data("max-length"))&&c.length>e?j(d,["Your edit summary cannot be longer than "+e+" characters."],o()):p(a,d)}},c))})}function t(a){var d=a.find(v);d.length&&d.blur(function(){e.push(setTimeout(function(){var c=d.val(),c=$.trim(c);if(0==c.length)p(a,d);else{var e=d.data("min-length");e&&c.length<e?j(d,["Wiki Excerpt must be at least "+e+" characters; you entered "+c.length+"."],o()):(e=d.data("max-length"))&&c.length>e?j(d,["Wiki Excerpt cannot be longer than "+e+" characters; you entered "+
c.length+"."],o()):p(a,d)}},c))})}function s(b){var d=b.find(a);d.length&&d.blur(function(){e.push(setTimeout(function(){var a=d.val();0==$.trim(a).length?p(b,d):/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,20}$/i.test(a)?p(b,d):j(d,["This email does not appear to be valid."],C())},c))})}function o(){var a=$("#sidebar, .sidebar").first().width()||270;return{position:{my:"left top",at:"right center"},css:{"max-width":a,"min-width":a},closeOthers:!1}}function C(){return{position:{my:"left top",at:"right center"},
css:{"min-width":$("#sidebar, .sidebar").first().width()||270},closeOthers:!1}}function y(b,d,c,e){if(b){var f=function(){var c=0;j(d.find(i),b.Title,o())?c++:p(d,d.find(i));j(d.find(w),b.Body,o())?c++:p(d,d.find(w));j(d.find(E),b.Tags,o())?c++:p(d,d.find(E));j(d.find(h),b.EditComment,o())?c++:p(d,d.find(h));j(d.find(v),b.Excerpt,o())?c++:p(d,d.find(v));j(d.find(a),b.Email,C())?c++:p(d,d.find(a));var f=d.find(".general-error"),g=b.General&&0<b.General.length;g||0<c?(f.length||(d.find('input[type="submit"]:visible').before('<div class="general-error-container"><div class="general-error"></div><br class="cbt" /></div>'),
f=d.find(".general-error")),g?j(f,b.General,{position:"inline",css:{"float":"left","margin-bottom":"10px"},closeOthers:!1,dismissable:!1}):(p(d,f),f.text("Your "+e+" couldn't be submitted. Please see the "+(1==c?"error":"errors")+" above."))):d.find(".general-error-container").remove();var m;B()&&($("#sidebar").animate({opacity:0.4},500),m=setInterval(function(){B()||($("#sidebar").animate({opacity:1},500),clearInterval(m))},500));var n;d.find(".validation-error").each(function(){var a=$(this).offset().top;
if(!n||a<n)n=a});c=function(){for(var a=0;3>a;a++)d.find(".message").animate({left:"+=5px"},100).animate({left:"-=5px"},100)};n?(f=$(".review-bar").length,n=Math.max(0,n-(f?125:30)),$("html, body").animate({scrollTop:n},c)):c()},m=function(){1!=c||d.find(E).length?f():setTimeout(m,250)};m()}}function j(a,d,c){if(!d||0==d.length||!a.length)return!1;if((d=1==d.length?d[0]:"<ul><li>"+d.join("</li><li>")+"</li></ul>")&&0<d.length){var e=a.data("error-popup");if(e&&e.is(":visible")){if(a.data("error-message")==
d)return!0;e.fadeOutAndRemove()}c=StackExchange.helpers.showMessage(a,d,c);c.find("a").attr("target","_blank");a.addClass("validation-error");a.data("error-popup",c);a.data("error-message",d);c.click(x);return!0}return!1}function p(a,c){if(!c||0==c.length)return!1;var e=c.data("error-popup");e&&e.is(":visible")&&e.fadeOutAndRemove();c.removeClass("validation-error");c.removeData("error-popup");c.removeData("error-message");a.find(".validation-error").length||a.find(".general-error-container").remove();
return!0}function B(){var a=!1,c=$("#sidebar, .sidebar").first();if(!c.length)return!1;var e=c.offset().left;$(".message").each(function(){var c=$(this);if(c.offset().left+c.outerWidth()>e)return a=!0,!1});return a}var i="input#title",w="textarea.wmd-input:first",E=".tag-editor",h="input[id^=edit-comment]",v="textarea#excerpt",a="input#m-address",e=[],c=250;return{initOnBlur:m,initOnBlurAndSubmit:function(a,c,e,f,i){m(a,c,f);var n,l=function(f){if(f.success)if(i)i(f);else{var h=window.location.href.split("#")[0],
j=f.redirectTo.split("#")[0];0==j.indexOf("/")&&(j=window.location.protocol+"//"+window.location.hostname+j);n=!0;window.location=f.redirectTo;h.toLowerCase()==j.toLowerCase()&&window.location.reload(!0)}else f.captchaHtml?StackExchange.captcha.init(f.captchaHtml,l):f.errors?y(f.errors,a,c,e):a.find('input[type="submit"]:visible').parent().showErrorMessage(f.message)};a.submit(function(){if(a.find("#answer-from-ask").is(":checked"))return!0;var c=a.find(h);if("[Edit removed during grace period]"==
$.trim(c.val()))return j(c,["Comment reserved for system use.  Please use an appropriate comment."],o()),!1;x();StackExchange.navPrevention&&StackExchange.navPrevention.stop();a.find('input[type="submit"]:visible').parent().addSpinner();StackExchange.helpers.disableSubmitButton(a);setTimeout(function(){$.ajax({type:"POST",dataType:"json",data:a.serialize(),url:a.attr("action"),success:l,error:function(){a.find('input[type="submit"]:visible').parent().showErrorMessage("An error occurred submitting the "+
e+".")},complete:function(){StackExchange.helpers.removeSpinner();n||StackExchange.helpers.enableSubmitButton(a)}})},0);return!1})},showErrorsAfterSubmission:y,getSidebarPopupOptions:o}}();
